language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - CODECLIMATE_REPO_TOKEN=99562fb63677adccafefa012c7aed9e4e2763e144457e0c1769a8895280885d6 ./vendor/bin/test-reporter
