language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
    composer global require "phpunit/phpcov"
    composer global require "codeclimate/php-test-reporter"
  - composer install
  - cd /tmp/wordpress/wp-content/plugins/ && git clone https://github.com/pcfreak30/rocket-async-css
  - git clone https://github.com/wp-media/wp-rocket
  - git clone https://github.com/Hube2/root-relative-urls
  - svn checkout http://plugins.svn.wordpress.org/the-preloader/trunk the-preloader -qq && cd ~

script:
  - phpunit --coverage-php logs/standalone.cov
  - TEST_PLUGIN="rocket-async-css/rocket-async-css.php,wp-rocket/wp-rocket.php,the-preloader/preloader.php" phpunit --coverage-php logs/rocket-async-css.cov --group rocket-async-css
  - TEST_PLUGIN="root-relative-urls/sb_root_relative_urls.php" phpunit --coverage-php logs/rocket-async-css.cov --group root-relative-urls

after_success:
  - phpcov merge --clover=logs/clover.xml logs/
  - .test-reporter -coverage-report=logs/clover.xml
